export const networks = [
  { id: 'ethereum', name: 'Ethereum', icon: null },
  { id: 'avalanche', name: 'Avalanche', icon: null },
  { id: 'arbitrum', name: 'Arbitrum', icon: null },

  // polkadot
  { id: 'aventus', name: 'Aventus', icon: null },
  { id: 'ajuna', name: 'Ajuna', icon: null },
  { id: 'bifrost', name: 'Bifrost', icon: null },
  { id: 'bitgreen', name: 'Bitgreen', icon: null },
  { id: 'collectives', name: 'Collectives', icon: null },
  { id: 'composable', name: 'Composable', icon: null },
  { id: 'crust', name: 'Crust', icon: null },
  { id: 'equilibrium', name: 'Equilibrium', icon: null },
  { id: 'frequency', name: 'Frequency', icon: null },
  { id: 'integritee', name: 'Integritee', icon: null },
  { id: 'interlay', name: 'Interlay', icon: null },
  { id: 'invarch', name: 'Invarch', icon: null },
  { id: 'kapex', name: 'Kapex', icon: null },
  { id: 'kilt-spiritnet', name: 'Kilt Spiritnet', icon: null },
  { id: 'litentry', name: 'Litentry', icon: null },
  { id: 'manta', name: 'Manta', icon: null },
  { id: 'nodle', name: 'Nodle', icon: null },
  { id: 'parallel', name: 'Parallel', icon: null },
  { id: 'pendulum', name: 'Pendulum', icon: null },
  { id: 'phala', name: 'Phala', icon: null },
  { id: 'polkadex', name: 'Polkadex', icon: null },
  { id: 'polkadot', name: 'Polkadot', icon: null },
  { id: 'polkadot-hashed', name: 'Polkadot hashed', icon: null },
  { id: 'statemint', name: 'Statemint', icon: null },
  { id: 'zeitgeist', name: 'Zeitgeist', icon: null },
  { id: 'clover', name: 'Clover', icon: null },
  { id: 'origintrail', name: 'Origintrail', icon: null },
  { id: 'hydradx', name: 'Hydradx', icon: null },
  { id: 'acala', name: 'Acala', icon: null },
  { id: 'astar', name: 'Astar', icon: null },
  { id: 'moonbeam', name: 'Moonbeam', icon: null },
  { id: 'darwinia', name: 'Darwinia', icon: null },
  { id: 'centrifuge', name: 'Centrifuge', icon: null },
  { id: 'unique', name: 'Unique', icon: null },
] as const;
