export const tokens = [
  { id: '1INCH', name: '1inch', icon: null },
  { id: 'AAVE', name: 'Aave', icon: null },
  { id: 'ADA', name: 'Cardano', icon: null },
  { id: 'APE', name: 'APECoin', icon: null },
  { id: 'ARB', name: 'Arbitrum', icon: null },
  { id: 'AVAX', name: 'Avalanche', icon: null },
  { id: 'BAL', name: 'Balancer', icon: null },
  { id: 'BNB', name: 'BNB', icon: null },
  { id: 'BTC', name: 'Bitcoin', icon: null },
  { id: 'BUSD', name: 'Binance USD', icon: null },
  { id: 'CAKE', name: 'Pancakeswap', icon: null },
  { id: 'COMP', name: 'Compound', icon: null },
  { id: 'CRV', name: 'Curve DAO', icon: null },
  { id: 'CRVUSD', name: 'crvUSD', icon: null },
  { id: 'CVX', name: 'Convex Finance', icon: null },
  { id: 'DAI', name: 'DAI', icon: null },
  { id: 'DOGE', name: 'Dogecoin', icon: null },
  { id: 'DOT', name: 'Polkadot', icon: null },
  { id: 'ENS', name: 'Ethereum Name Service', icon: null },
  { id: 'ETH', name: 'Ethereum', icon: null },
  { id: 'EURT', name: 'Tether Euro', icon: null },
  { id: 'FXS', name: 'Frax Share', icon: null },
  { id: 'GRT', name: 'The Graph', icon: null },
  { id: 'HBAR', name: 'Hedera Hashgraph', icon: null },
  { id: 'HIGH', name: 'Highstreet', icon: null },
  { id: 'IMX', name: 'Immutable X', icon: null },
  { id: 'KNC', name: 'Kyber Network', icon: null },
  { id: 'LINK', name: 'Chainlink', icon: null },
  { id: 'LTC', name: 'Litecoin', icon: null },
  { id: 'MATIC', name: 'Polygon (MATIC)', icon: null },
  { id: 'MKR', name: 'Maker', icon: null },
  { id: 'PERP', name: 'Perpetual Protocol', icon: null },
  { id: 'RDNT', name: 'Radiant Capital', icon: null },
  { id: 'RPL', name: 'Rocket Pool', icon: null },
  { id: 'RSR', name: 'Reserve Rights', icon: null },
  { id: 'SAND', name: 'The Sandbox', icon: null },
  { id: 'SNX', name: 'Synthetix Network', icon: null },
  { id: 'SOL', name: 'Solana', icon: null },
  { id: 'SPELL', name: 'Spell Token', icon: null },
  { id: 'STETH', name: 'Lido Staked ETH', icon: null },
  { id: 'STG', name: 'Stargate Finance', icon: null },
  { id: 'SUSHI', name: 'Sushi', icon: null },
  { id: 'SXP', name: 'Swipe', icon: null },
  { id: 'TUSD', name: 'True USD', icon: null },
  { id: 'UNI', name: 'Uniswap', icon: null },
  { id: 'USDC', name: 'Circle USD', icon: null },
  { id: 'USDD', name: 'USDD', icon: null },
  { id: 'USDP', name: 'Pax Dollar', icon: null },
  { id: 'USDT', name: 'Tether USD', icon: null },
  { id: 'WING', name: 'Wing Finance', icon: null },
  { id: 'XCN', name: 'Chain', icon: null },
  { id: 'YFI', name: 'Yearn Finance', icon: null },
];
